### ISSUE TITLE
UIFields not working

### ISSUE THREAD

**Issue by thorbenegberts** [7MinDev/gwt-polymer-ui-framework#2]
`MyView` => code is currently commented out ... compile errors ... help wanted :-)

**Comment by pschmidt88** [comment]
In der IDE werden die als UIFields als Errors angezeigt, das ist ganz normal.

Beim compilen musst du das JsInterop flag setzen. (-XjsInteropMode CLOSURE oder so.)

**Comment by thorbenegberts** [comment]
![bildschirmfoto 2015-01-31 um 12 34 59](https://cloud.githubusercontent.com/assets/3115618/5987912/328a3ed4-a946-11e4-9e10-e117a0598fe4.png)
![bildschirmfoto 2015-01-31 um 12 32 33](https://cloud.githubusercontent.com/assets/3115618/5987911/3288d472-a946-11e4-93c6-78060c0ccedc.png)

**Comment by thorbenegberts** [comment]
ah okay ... ich versuchs ... kann man das auch in den modul-eigenschaften setzen?

**Comment by pschmidt88** [comment]
![bildschirmfoto 2015-01-31 um 12 41 11](https://cloud.githubusercontent.com/assets/465359/5987918/7c030d48-a946-11e4-99d3-8cdbb1b6f36f.png)

**Comment by thorbenegberts** [comment]
done :-) danke @rookian1337 

![bildschirmfoto 2015-01-31 um 12 54 11](https://cloud.githubusercontent.com/assets/3115618/5987961/6e05f51e-a948-11e4-8e15-1b09fa1ed62f.png)

@florian-f @luQx vll ist das auch was für euch zum spielen ;-) In der Readme steht, wie man es zum laufen bekommt
